### ISSUE TITLE
Pretraining data

### ISSUE THREAD

**Issue by swj0419** [facebookresearch/contriever#3]
Great work! Thanks for sharing the model and code. I was wondering if you can share the pertaining data or the code to generate positive pairs from the pretraining corpus. Thank you in advance!

**Comment by gizacard** [comment]
Code for pre-training has been released.
Regarding the data we performed pre-training on a mix of Wikipedia and CCNet data, instructions to reproduce pre-processing are now in the repository.

Gautier
