### ISSUE TITLE
Default value -1 for main_port in eval_beir.py may raise error

### ISSUE THREAD

**Issue by ziqing-huang** [facebookresearch/contriever#4]
Thanks for providing this great work!

I note that you set the default value of `main_port` as -1 in `eval_beir.py`, which raise an error when I run

`python eval_beir.py --model_name_or_path facebook/contriever-msmarco --dataset scifact`

directly. I set this value to 10001 and solved the problem. I suggest that you can change the default value or add one line to README.

**Comment by gizacard** [comment]
Done, changed it to 10001. However this will raise an error if the evaluation is performed on the same machine with multi gpus with no specific port specified, I don't have a better solution as of now.

Gautier
